import type { OrientationContent } from './types';

// Business narrative summarised from the SERIS IG, Business Context > Use Cases:
// https://simplifier.net/guide/ca-on-seris-r4-iguide/Table-of-Contents/BusinessContext/Use-Cases?version=1.1.0
// Every artifact reference below is validated against SPEC at module load
// (see ./validate.ts). Example payloads use real codes from the IG's code
// systems and are illustrative skeletons, not conformance-tested instances.

const SD = 'http://ontariohealth.ca/fhir/StructureDefinition';
const CS = 'http://ontariohealth.ca/fhir/CodeSystem';
const profileUrl = (n: string) => `${SD}/ca-on-seris-profile-${n}`;

export const ORIENTATION: OrientationContent = {
  sourceUrl:
    'https://simplifier.net/guide/ca-on-seris-r4-iguide/Table-of-Contents/BusinessContext/Use-Cases?version=1.1.0',
  intro: {
    headline: 'How surgical operations become FHIR data',
    what: 'SERIS — the Surgical Efficiency Reporting Information System — captures operating-room schedules and surgical cases in near-real-time so Ontario Health and hospitals can see surgical capacity, waitlists, cancellations, and bottlenecks across the province. This guide walks the surgical business workflow and, for each real-world event, shows the exact FHIR output it produces. Click any artifact chip to open it in the full Reference explorer.',
    actors: [
      { name: 'Designated OR Personnel', role: 'Hospital staff who schedule OR time and record case outcomes' },
      { name: "Surgeon's office", role: 'Requests and books elective surgical cases' },
      { name: 'OR scheduling / HIS systems', role: 'Hospital systems that generate the data and publish it as FHIR' },
      { name: 'Ontario Health', role: 'Operates the provincial repository that receives and analyses the data' },
    ],
    dataFlow:
      'Hospital OR scheduling and health-information systems publish FHIR messages (a Bundle led by a MessageHeader) to the Ontario Health provincial repository. OR Schedule events describe capacity (rooms, schedules, blocks, slots); OR Case events describe each surgical case as it moves booked → performed or cancelled.',
    howToUse:
      'Start with the Key Journey for the end-to-end story, then open the OR Schedule or OR Case tracks to see every use case in detail — each with the FHIR artifacts it produces, an illustrative example, and the profile’s generated template.',
  },

  keyJourneyStepIds: [
    'sched-room',
    'sched-create',
    'sched-add-block',
    'case-book',
    'case-perform',
    'case-cancel',
    'case-submit',
  ],

  tracks: [
    // ----------------------------------------------------------------- OR SCHEDULE
    {
      id: 'schedule',
      title: 'OR Schedule lifecycle',
      summary:
        'Setting up and maintaining operating-room capacity: rooms, schedules, surgical blocks, and slots. Driven by the Location, Schedule, and Slot profiles and their block/shift/hours extensions.',
      stages: [
        { title: 'Set up capacity', stepIds: ['sched-room', 'sched-create', 'sched-create-slot'] },
        {
          title: 'Allocate & adjust blocks',
          stepIds: ['sched-add-block', 'sched-modify-block', 'sched-adjust-block', 'sched-remove-block'],
        },
        {
          title: 'Maintain slots, rooms & horizon',
          stepIds: ['sched-slot-duration', 'sched-room-details', 'sched-shift-hours', 'sched-horizon'],
        },
        { title: 'Closures', stepIds: ['sched-close', 'sched-temp-close', 'sched-perm-close'] },
        { title: 'Corrections', stepIds: ['sched-eie', 'sched-remove-slot'] },
      ],
      steps: [
        {
          id: 'sched-room',
          ucRef: 'OR Schedule · UC16',
          title: 'Create a new OR room',
          event: 'Designated OR Personnel register a new operating room for a site — the physical space surgery happens in.',
          actor: 'Designated OR Personnel',
          action: 'POST',
          primaryProfile: 'Location',
          artifacts: [
            { kind: 'profile', name: 'Location', group: 'produces' },
            { kind: 'extension', name: 'ORUnit', group: 'extends' },
            { kind: 'extension', name: 'FunctionalCentre', group: 'extends' },
            { kind: 'extension', name: 'MisFunctionalCentre', group: 'extends' },
            { kind: 'valueSet', name: 'LocationFunctionalCentre', group: 'codes' },
          ],
          example: {
            title: 'Location — a new OR',
            description: 'A worked Location instance: the same must-support elements as the profile template, filled in, plus the OR Unit extension.',
            json: {
              resourceType: 'Location',
              meta: { profile: [profileUrl('Location')] },
              extension: [{ url: `${SD}/ca-on-seris-ext-or-unit`, valueString: 'Main OR Suite' }],
              identifier: [{ system: 'http://hospital.example/locations', value: 'OR-3' }],
              status: 'active',
              name: 'OR-3',
              type: [{ coding: [{ system: `${CS}/location-functional-centre`, code: '71350', display: 'Specialty Clinic' }] }],
              partOf: { reference: 'Organization/site-hospital' },
            },
            annotations: [
              { path: 'extension', note: 'ORUnit extension — the OR unit this room belongs to.' },
              { path: 'status', note: 'active = the room is in use; set to inactive to decommission it (UC12).' },
              { path: 'type', note: 'Functional centre code from LocationFunctionalCentre.' },
              { path: 'partOf', note: 'Links the room to its site (Organization).' },
            ],
          },
        },
        {
          id: 'sched-create',
          ucRef: 'OR Schedule · UC1',
          title: 'Create a new OR schedule',
          event: 'Personnel open a fresh schedule for a shift — declaring when a room is available for surgery.',
          actor: 'Designated OR Personnel',
          action: 'POST',
          primaryProfile: 'Schedule',
          artifacts: [
            { kind: 'profile', name: 'Schedule', group: 'produces' },
            { kind: 'extension', name: 'ShiftType', group: 'extends' },
            { kind: 'extension', name: 'HoursOfOperation', group: 'extends' },
            { kind: 'profile', name: 'Location', group: 'produces' },
          ],
          example: {
            title: 'Schedule — an OR shift',
            description: 'The must-support Schedule elements filled in, plus the shift-type and hours-of-operation extensions.',
            json: {
              resourceType: 'Schedule',
              meta: { profile: [profileUrl('Schedule')] },
              extension: [
                { url: `${SD}/ca-on-seris-ext-shift-type`, valueString: 'Day' },
                {
                  url: `${SD}/ca-on-seris-ext-hours-of-operation`,
                  extension: [
                    { url: 'startTime', valueTime: '07:30:00' },
                    { url: 'stopTime', valueTime: '15:30:00' },
                    { url: 'daysOfWeek', valueString: 'Mon-Fri' },
                  ],
                },
              ],
              identifier: [{ system: 'http://hospital.example/schedules', value: 'SCH-OR3-2025-06-02' }],
              active: true,
              actor: [{ reference: 'Location/or-3' }],
              planningHorizon: { start: '2025-06-02T07:30:00-04:00', end: '2025-06-02T15:30:00-04:00' },
            },
            annotations: [
              { path: 'extension', note: 'ShiftType + HoursOfOperation (start/stop/days) extensions.' },
              { path: 'actor', note: 'References the OR room (Location) this schedule is for.' },
              { path: 'planningHorizon', note: 'The shift window; closing a schedule (UC7) shortens this.' },
            ],
          },
        },
        {
          id: 'sched-create-slot',
          ucRef: 'OR Schedule · UC6',
          title: 'Create a new slot',
          event: 'Personnel add a slot inside an existing schedule — a bookable (or blocked) sub-interval of the shift.',
          actor: 'Designated OR Personnel',
          action: 'POST',
          primaryProfile: 'Slot',
          artifacts: [
            { kind: 'profile', name: 'Slot', group: 'produces' },
            { kind: 'profile', name: 'Schedule', group: 'produces' },
            { kind: 'extension', name: 'SlotName', group: 'extends' },
          ],
        },
        {
          id: 'sched-add-block',
          ucRef: 'OR Schedule · UC2',
          title: 'Add a block to the schedule',
          event: 'A surgical block is assigned to an open slot for a specific service and surgeon(s) — reserving recurring OR time for a specialty.',
          actor: 'Designated OR Personnel',
          action: 'POST',
          primaryProfile: 'Slot',
          artifacts: [
            { kind: 'profile', name: 'Slot', group: 'produces' },
            { kind: 'extension', name: 'SERISBlock', group: 'extends' },
            { kind: 'extension', name: 'BlockService', group: 'extends' },
            { kind: 'extension', name: 'BlockSurgeons', group: 'extends' },
            { kind: 'valueSet', name: 'HospitalService', group: 'codes' },
          ],
          example: {
            title: 'Slot — a surgical block',
            description: 'The must-support Slot elements filled in, plus the SERIS Block extension naming the service and surgeon(s).',
            json: {
              resourceType: 'Slot',
              meta: { profile: [profileUrl('Slot')] },
              extension: [
                {
                  url: `${SD}/ca-on-seris-ext-block`,
                  extension: [
                    { url: 'blockService', valueCodeableConcept: { coding: [{ system: 'http://snomed.info/sct', code: '310142007', display: 'Cardiac surgery service' }] } },
                    { url: 'blockSurgeons', valueIdentifier: { system: 'http://example.org/cpso', value: '12345' } },
                  ],
                },
              ],
              identifier: [{ system: 'http://hospital.example/slots', value: 'SLOT-1' }],
              serviceType: [{ coding: [{ system: 'http://snomed.info/sct', code: '310142007', display: 'Cardiac surgery service' }] }],
              schedule: { reference: 'Schedule/sch-or3-2025-06-02' },
              status: 'busy-unavailable',
              start: '2025-06-02T07:30:00-04:00',
              end: '2025-06-02T11:30:00-04:00',
            },
            annotations: [
              { path: 'extension', note: 'The SERISBlock extension bundles blockService + blockSurgeons sub-extensions.' },
              { path: 'serviceType', note: 'The surgical service the block is for (HospitalService / SNOMED).' },
              { path: 'status', note: 'busy-unavailable marks the time as reserved by the block.' },
              { path: 'schedule', note: 'Every Slot points back to its parent Schedule.' },
            ],
          },
        },
        {
          id: 'sched-modify-block',
          ucRef: 'OR Schedule · UC4',
          title: 'Modify a block’s surgeon / service',
          event: 'The service or surgeon allocated to a block is reassigned, recording why the block changed.',
          actor: 'Designated OR Personnel',
          action: 'POST',
          primaryProfile: 'Slot',
          artifacts: [
            { kind: 'profile', name: 'Slot', group: 'produces' },
            { kind: 'extension', name: 'SERISBlockChange', group: 'extends' },
            { kind: 'valueSet', name: 'BlockChangeReason', group: 'codes' },
          ],
        },
        {
          id: 'sched-adjust-block',
          ucRef: 'OR Schedule · UC5',
          title: 'Adjust block metadata',
          event: 'Block operational parameters — release frequency and auto-release hours — are fine-tuned without changing the service or surgeon.',
          actor: 'Designated OR Personnel',
          action: 'POST',
          primaryProfile: 'Slot',
          artifacts: [
            { kind: 'profile', name: 'Slot', group: 'produces' },
            { kind: 'extension', name: 'SETPBlockFrequency', group: 'extends' },
            { kind: 'extension', name: 'SETPBlockAutoRelease', group: 'extends' },
          ],
        },
        {
          id: 'sched-remove-block',
          ucRef: 'OR Schedule · UC3',
          title: 'Release a block',
          event: 'A block is deallocated from its slot — releasing the reserved surgeon/service time back to the pool, with a release reason.',
          actor: 'Designated OR Personnel',
          action: 'POST',
          primaryProfile: 'Slot',
          artifacts: [
            { kind: 'profile', name: 'Slot', group: 'produces' },
            { kind: 'extension', name: 'SERISBlockRelease', group: 'extends' },
            { kind: 'valueSet', name: 'BlockReleaseReason', group: 'codes' },
          ],
          example: {
            title: 'Slot — block released',
            description: 'The same Slot, now free, carrying the SERIS Block Release extension (a complex extension with reason and date sub-extensions).',
            json: {
              resourceType: 'Slot',
              meta: { profile: [profileUrl('Slot')] },
              extension: [
                {
                  url: `${SD}/ca-on-seris-ext-block-release`,
                  extension: [
                    { url: 'releaseReason', valueCodeableConcept: { coding: [{ system: `${CS}/block-release-reason`, code: 'sr', display: 'Surgeon Request' }] } },
                    { url: 'releaseDate', valueDateTime: '2025-05-30T09:00:00-04:00' },
                  ],
                },
              ],
              identifier: [{ system: 'http://hospital.example/slots', value: 'SLOT-1' }],
              serviceType: [{ coding: [{ system: 'http://snomed.info/sct', code: '310142007', display: 'Cardiac surgery service' }] }],
              schedule: { reference: 'Schedule/sch-or3-2025-06-02' },
              status: 'free',
              start: '2025-06-02T07:30:00-04:00',
              end: '2025-06-02T11:30:00-04:00',
            },
            annotations: [
              { path: 'extension', note: 'SERISBlockRelease: releaseReason "sr" = Surgeon Request, plus the release date.' },
              { path: 'status', note: 'free = the time is available again once the block is released.' },
            ],
          },
        },
        {
          id: 'sched-slot-duration',
          ucRef: 'OR Schedule · UC8',
          title: 'Modify slot duration',
          event: 'Slot lengths are adjusted, compensating neighbouring slots so the shift stays continuous (no gaps or overlaps).',
          actor: 'Designated OR Personnel',
          action: 'POST',
          primaryProfile: 'Slot',
          artifacts: [
            { kind: 'profile', name: 'Slot', group: 'produces' },
            { kind: 'profile', name: 'Schedule', group: 'produces' },
          ],
        },
        {
          id: 'sched-room-details',
          ucRef: 'OR Schedule · UC9',
          title: 'Update OR room details',
          event: 'A room’s name, MIS functional centre, functional centre, or operational status is updated.',
          actor: 'Designated OR Personnel',
          action: 'POST',
          primaryProfile: 'Location',
          artifacts: [
            { kind: 'profile', name: 'Location', group: 'produces' },
            { kind: 'extension', name: 'MisFunctionalCentre', group: 'extends' },
            { kind: 'valueSet', name: 'MISFunctionalCentre', group: 'codes' },
          ],
        },
        {
          id: 'sched-shift-hours',
          ucRef: 'OR Schedule · UC10',
          title: 'Modify shift operating hours',
          event: 'Future shift availability is changed by closing the current schedule and creating a replacement (UC7 + UC1).',
          actor: 'Designated OR Personnel',
          action: 'POST',
          primaryProfile: 'Schedule',
          artifacts: [
            { kind: 'profile', name: 'Schedule', group: 'produces' },
            { kind: 'profile', name: 'Location', group: 'produces' },
            { kind: 'extension', name: 'HoursOfOperationAdjustment', group: 'extends' },
          ],
        },
        {
          id: 'sched-horizon',
          ucRef: 'OR Schedule · UC13',
          title: 'Update the planning horizon',
          event: 'The scheduling window is extended or modified by closing the current schedule and creating a new one.',
          actor: 'Designated OR Personnel',
          action: 'POST',
          primaryProfile: 'Schedule',
          artifacts: [
            { kind: 'profile', name: 'Schedule', group: 'produces' },
            { kind: 'extension', name: 'SETPScheduleWeek', group: 'extends' },
          ],
        },
        {
          id: 'sched-close',
          ucRef: 'OR Schedule · UC7',
          title: 'Close an OR schedule',
          event: 'A schedule is inactivated by shortening its planning horizon — ending availability for that shift.',
          actor: 'Designated OR Personnel',
          action: 'POST',
          primaryProfile: 'Schedule',
          artifacts: [{ kind: 'profile', name: 'Schedule', group: 'produces' }],
        },
        {
          id: 'sched-temp-close',
          ucRef: 'OR Schedule · UC11',
          title: 'Temporary OR closure',
          event: 'All slots are marked unavailable for a closure period, with a stated reason (e.g. holidays, environmental, human resources).',
          actor: 'Designated OR Personnel',
          action: 'POST',
          primaryProfile: 'Slot',
          artifacts: [
            { kind: 'profile', name: 'Schedule', group: 'produces' },
            { kind: 'profile', name: 'Slot', group: 'produces' },
            { kind: 'extension', name: 'SETPClosure', group: 'extends' },
            { kind: 'valueSet', name: 'ORClosureReason', group: 'codes' },
          ],
          example: {
            title: 'Slot — temporary closure',
            description: 'Each affected Slot is made unavailable, carrying the closure reason via the SETP Closure extension.',
            json: {
              resourceType: 'Slot',
              meta: { profile: [profileUrl('Slot')] },
              extension: [
                {
                  url: `${SD}/ca-on-setp-ext-closures`,
                  valueCodeableConcept: { coding: [{ system: `${CS}/or-closure-reason`, code: 'p-h', display: 'Planned-Holidays' }] },
                },
              ],
              identifier: [{ system: 'http://hospital.example/slots', value: 'SLOT-7' }],
              serviceType: [{ coding: [{ system: 'http://snomed.info/sct', code: '310142007', display: 'Cardiac surgery service' }] }],
              schedule: { reference: 'Schedule/sch-or3-2025-07-01' },
              status: 'busy-unavailable',
              start: '2025-07-01T07:30:00-04:00',
              end: '2025-07-01T15:30:00-04:00',
            },
            annotations: [
              { path: 'extension', note: 'SETPClosure with ORClosureReason "p-h" = Planned-Holidays.' },
              { path: 'status', note: 'busy-unavailable across the closure period.' },
            ],
          },
        },
        {
          id: 'sched-perm-close',
          ucRef: 'OR Schedule · UC12',
          title: 'Permanent OR room closure',
          event: 'A room is decommissioned: all its schedules are closed and the Location is marked inactive.',
          actor: 'Designated OR Personnel',
          action: 'POST',
          primaryProfile: 'Location',
          artifacts: [
            { kind: 'profile', name: 'Location', group: 'produces' },
            { kind: 'profile', name: 'Schedule', group: 'produces' },
          ],
        },
        {
          id: 'sched-eie',
          ucRef: 'OR Schedule · UC14',
          title: 'Mark data entered in error',
          event: 'A schedule, slot, or location created by mistake is flagged as entered-in-error for data-quality correction.',
          actor: 'Designated OR Personnel',
          action: 'POST',
          primaryProfile: 'Slot',
          artifacts: [
            { kind: 'profile', name: 'Schedule', group: 'produces' },
            { kind: 'profile', name: 'Slot', group: 'produces' },
            { kind: 'profile', name: 'Location', group: 'produces' },
            { kind: 'extension', name: 'StatusRemoved', group: 'extends' },
          ],
        },
        {
          id: 'sched-remove-slot',
          ucRef: 'OR Schedule · UC15',
          title: 'Remove a block or slot',
          event: 'A block or slot is deleted from an active schedule — reducing capacity or removing an erroneous entry.',
          actor: 'Designated OR Personnel',
          action: 'POST',
          primaryProfile: 'Slot',
          artifacts: [
            { kind: 'profile', name: 'Slot', group: 'produces' },
            { kind: 'profile', name: 'Schedule', group: 'produces' },
          ],
        },
      ],
    },

    // ----------------------------------------------------------------- OR CASE
    {
      id: 'case',
      title: 'OR Case lifecycle',
      summary:
        'The surgical case from booking to outcome, modelled as Encounter state transitions (booked → performed / cancelled / entered-in-error), with Procedure, MedicationAdministration, and Observation capturing what happened. Cases are published to the repository in a message Bundle.',
      stages: [
        { title: 'Book', stepIds: ['case-book', 'case-update-booked'] },
        { title: 'Perform', stepIds: ['case-perform', 'case-update-performed', 'case-addon'] },
        { title: 'Cancel', stepIds: ['case-cancel', 'case-cancel-addon'] },
        { title: 'Corrections', stepIds: ['case-eie'] },
        { title: 'Report', stepIds: ['case-submit'] },
      ],
      steps: [
        {
          id: 'case-book',
          ucRef: 'OR Case · UC1',
          title: 'Book elective surgery',
          event: 'An OR is booked for a new elective case and the case details are entered. The case enters the "booked" state.',
          actor: "Designated OR Personnel · Surgeon's office",
          action: 'POST',
          caseState: 'booked',
          primaryProfile: 'Encounter',
          artifacts: [
            { kind: 'profile', name: 'Encounter', group: 'produces' },
            { kind: 'profile', name: 'Patient', group: 'produces' },
            { kind: 'extension', name: 'SETPSurgicalPriority', group: 'extends' },
            { kind: 'extension', name: 'SETPBookingDate', group: 'extends' },
            { kind: 'valueSet', name: 'BusinessStatus', group: 'codes' },
            { kind: 'valueSet', name: 'SurgicalPriorityClassification', group: 'codes' },
            { kind: 'valueSet', name: 'EncounterClass', group: 'codes' },
          ],
          example: {
            title: 'Encounter — booked case',
            description: 'A planned elective encounter with the must-support Encounter elements filled in. Surgical priority is the required Encounter.priority element.',
            json: {
              resourceType: 'Encounter',
              meta: { profile: [profileUrl('Encounter')] },
              status: 'planned',
              class: { system: 'http://terminology.hl7.org/CodeSystem/v3-ActCode', code: 'AMB', display: 'ambulatory' },
              type: [{ coding: [{ system: 'http://cihi.ca/fhir/CodeSystem/aac-admit-category', code: 'L', display: 'Elective' }] }],
              priority: { coding: [{ system: `${CS}/surgical-priority-classification`, code: 'P1D', display: 'Access within 2-7 days' }] },
              subject: { reference: 'Patient/example' },
              appointment: [{ reference: 'Appointment/case-123' }],
              period: { start: '2025-06-02T07:30:00-04:00' },
              reasonReference: [{ reference: 'Procedure/planned-tkr' }],
            },
            annotations: [
              { path: 'status', note: 'Encounter.status "planned" corresponds to the SERIS "booked" business state.' },
              { path: 'type', note: 'EncounterType "L" = Elective admission category.' },
              { path: 'priority', note: 'Required Encounter.priority — surgical priority P1D = access within 2–7 days.' },
              { path: 'subject', note: 'Links the case to the Patient profile.' },
            ],
          },
        },
        {
          id: 'case-update-booked',
          ucRef: 'OR Case · UC2',
          title: 'Update a booked case',
          event: 'Pre-operative details of a scheduled case are changed — e.g. its OR/location assignment.',
          actor: 'Designated OR Personnel',
          action: 'POST',
          caseState: 'booked',
          primaryProfile: 'Encounter',
          artifacts: [
            { kind: 'profile', name: 'Encounter', group: 'produces' },
            { kind: 'profile', name: 'Location', group: 'produces' },
          ],
        },
        {
          id: 'case-perform',
          ucRef: 'OR Case · UC3',
          title: 'Record a performed case',
          event: 'After surgery, the performed procedure is documented for a booked case — including anaesthesia, the surgical-safety checklist, and observations. The case moves to "performed".',
          actor: 'Designated OR Personnel',
          action: 'POST',
          caseState: 'performed',
          primaryProfile: 'Procedure',
          artifacts: [
            { kind: 'profile', name: 'Encounter', group: 'produces' },
            { kind: 'profile', name: 'Procedure', group: 'produces' },
            { kind: 'profile', name: 'MedicationAdministration', group: 'produces' },
            { kind: 'profile', name: 'Observation', group: 'produces' },
            { kind: 'extension', name: 'InRoom', group: 'extends' },
            { kind: 'extension', name: 'SERISSurgicalChecklist', group: 'extends' },
            { kind: 'extension', name: 'SETPAnaesthesia Type', group: 'extends' },
            { kind: 'valueSet', name: 'AnaesthesiaType', group: 'codes' },
            { kind: 'valueSet', name: 'ASAphysicalStatus', group: 'codes' },
            { kind: 'valueSet', name: 'ProcedureComplication', group: 'codes' },
          ],
          example: {
            title: 'Procedure — performed surgery',
            description: 'The must-support Procedure elements filled in, plus the in-room period, surgical-safety checklist, and anaesthesia type extensions.',
            json: {
              resourceType: 'Procedure',
              meta: { profile: [profileUrl('Procedure')] },
              extension: [
                { url: `${SD}/ca-on-seris-ext-in-room`, valuePeriod: { start: '2025-06-02T08:05:00-04:00', end: '2025-06-02T09:40:00-04:00' } },
                { url: `${SD}/ca-on-seris-ext-surgicalchecklist`, valueBoolean: true },
                { url: `${SD}/ca-on-setp-ext-anaesthesiatype`, valueCodeableConcept: { coding: [{ system: 'http://snomed.info/sct', code: '50697003', display: 'General anesthesia' }] } },
              ],
              status: 'completed',
              category: [{ coding: [{ system: 'http://snomed.info/sct', code: '310142007', display: 'Cardiac surgery service' }] }],
              code: { coding: [{ system: 'http://snomed.info/sct', code: '179342005', display: 'Total knee replacement' }] },
              subject: { reference: 'Patient/example' },
              performedPeriod: { start: '2025-06-02T08:20:00-04:00', end: '2025-06-02T09:25:00-04:00' },
              performer: [{ actor: { reference: 'PractitionerRole/surgeon-1' } }],
              location: { reference: 'Location/or-3' },
              complication: [{ coding: [{ system: 'http://snomed.info/sct', code: '131148009', display: 'Bleeding' }] }],
            },
            annotations: [
              { path: 'extension', note: 'InRoom (wheels-in to wheels-out — central to OR efficiency), surgical checklist, and anaesthesia type.' },
              { path: 'performedPeriod', note: 'When the surgery actually happened (the performed[x] choice element).' },
              { path: 'performer', note: 'The operating surgeon (PractitionerRole).' },
              { path: 'complication', note: 'Any intra-operative complication, from ProcedureComplication.' },
            ],
          },
        },
        {
          id: 'case-update-performed',
          ucRef: 'OR Case · UC4',
          title: 'Update a performed case',
          event: 'Procedure information is refined or corrected after the surgery is complete.',
          actor: 'Designated OR Personnel',
          action: 'POST',
          caseState: 'performed',
          primaryProfile: 'Procedure',
          artifacts: [
            { kind: 'profile', name: 'Encounter', group: 'produces' },
            { kind: 'profile', name: 'Procedure', group: 'produces' },
            { kind: 'profile', name: 'Observation', group: 'produces' },
          ],
        },
        {
          id: 'case-addon',
          ucRef: 'OR Case · UC6',
          title: 'Perform an add-on case',
          event: 'An unscheduled urgent/emergency case is performed and documented — there was no prior booking.',
          actor: 'Designated OR Personnel',
          action: 'POST',
          caseState: 'performed',
          primaryProfile: 'Encounter',
          artifacts: [
            { kind: 'profile', name: 'Encounter', group: 'produces' },
            { kind: 'profile', name: 'Procedure', group: 'produces' },
            { kind: 'valueSet', name: 'EncounterType', group: 'codes' },
          ],
        },
        {
          id: 'case-cancel',
          ucRef: 'OR Case · UC5',
          title: 'Cancel an elective case',
          event: 'A scheduled case is cancelled in advance or same-day (including in-room). The cancellation date, reason, and any rescheduled date are recorded; the case moves to "cancelled".',
          actor: 'Designated OR Personnel',
          action: 'POST',
          caseState: 'cancelled',
          primaryProfile: 'Encounter',
          artifacts: [
            { kind: 'profile', name: 'Encounter', group: 'produces' },
            { kind: 'extension', name: 'SERISCancellation', group: 'extends' },
            { kind: 'extension', name: 'SERISReschedule', group: 'extends' },
            { kind: 'valueSet', name: 'SurgeryCancellationReason', group: 'codes' },
          ],
          example: {
            title: 'Encounter — cancelled case',
            description: 'The same booked Encounter, now cancelled, with the SERIS Cancellation and Reschedule extensions. Same must-support fields as the booked example.',
            json: {
              resourceType: 'Encounter',
              meta: { profile: [profileUrl('Encounter')] },
              extension: [
                {
                  url: `${SD}/ca-on-seris-ext-cancellation`,
                  extension: [
                    { url: 'CancellationReason', valueCodeableConcept: { coding: [{ system: `${CS}/surgery-cancellation-reason`, code: 'advw-104', display: 'Adverse Weather - Patient' }] } },
                    { url: 'CancellationDate', valueDateTime: '2025-06-01T16:20:00-04:00' },
                  ],
                },
                {
                  url: `${SD}/ca-on-seris-ext-reschedule`,
                  extension: [
                    { url: 'rescheduleFlag', valueBoolean: true },
                    { url: 'rescheduleDate', valueDateTime: '2025-06-09T07:30:00-04:00' },
                  ],
                },
              ],
              status: 'cancelled',
              class: { system: 'http://terminology.hl7.org/CodeSystem/v3-ActCode', code: 'AMB', display: 'ambulatory' },
              type: [{ coding: [{ system: 'http://cihi.ca/fhir/CodeSystem/aac-admit-category', code: 'L', display: 'Elective' }] }],
              priority: { coding: [{ system: `${CS}/surgical-priority-classification`, code: 'P1D', display: 'Access within 2-7 days' }] },
              subject: { reference: 'Patient/example' },
              appointment: [{ reference: 'Appointment/case-123' }],
              period: { start: '2025-06-02T07:30:00-04:00' },
              reasonReference: [{ reference: 'Procedure/planned-tkr' }],
            },
            annotations: [
              { path: 'status', note: 'Encounter.status "cancelled" = the SERIS "cancelled" business state.' },
              { path: 'extension', note: 'SERISCancellation (reason from SurgeryCancellationReason + date) and SERISReschedule (flag + new date).' },
            ],
          },
        },
        {
          id: 'case-cancel-addon',
          ucRef: 'OR Case · UC7',
          title: 'Cancel an add-on case',
          event: 'An in-room cancellation of an unscheduled add-on case is captured.',
          actor: 'Designated OR Personnel',
          action: 'POST',
          caseState: 'cancelled',
          primaryProfile: 'Encounter',
          artifacts: [
            { kind: 'profile', name: 'Encounter', group: 'produces' },
            { kind: 'extension', name: 'SERISCancellation', group: 'extends' },
            { kind: 'valueSet', name: 'SurgeryCancellationReason', group: 'codes' },
          ],
        },
        {
          id: 'case-eie',
          ucRef: 'OR Case · UC8',
          title: 'Mark a case entered in error',
          event: 'A case recorded by mistake is cancelled with a reason of entered-in-error.',
          actor: 'Designated OR Personnel',
          action: 'POST',
          caseState: 'entered-in-error',
          primaryProfile: 'Encounter',
          artifacts: [
            { kind: 'profile', name: 'Encounter', group: 'produces' },
            { kind: 'valueSet', name: 'BusinessStatus', group: 'codes' },
          ],
        },
        {
          id: 'case-submit',
          title: 'Submit to the SERIS repository',
          event: 'Each case event is published to the Ontario Health provincial repository as a FHIR message — a Bundle led by a MessageHeader — with a Task tracking the case’s business status.',
          actor: 'OR scheduling / HIS systems',
          action: 'message',
          primaryProfile: 'MessageHeader',
          artifacts: [
            { kind: 'profile', name: 'Bundle', group: 'produces' },
            { kind: 'profile', name: 'MessageHeader', group: 'produces' },
            { kind: 'profile', name: 'Task', group: 'produces' },
            { kind: 'valueSet', name: 'MessageEventCode', group: 'codes' },
            { kind: 'valueSet', name: 'BusinessStatus', group: 'codes' },
            { kind: 'capability', name: 'SERISClientFHIRCapabilityStatement', group: 'produces' },
          ],
          example: {
            title: 'MessageHeader — case event',
            description: 'The MessageHeader names the business event that triggered the message; it leads a Bundle of the case resources.',
            json: {
              resourceType: 'MessageHeader',
              meta: { profile: [profileUrl('MessageHeader')] },
              eventCoding: { system: `${CS}/message-event-code`, code: 'case-performed', display: 'Case performed' },
              source: { endpoint: 'https://his.hospital.example/fhir' },
              focus: [{ reference: 'Task/case-123' }],
            },
            annotations: [
              { path: 'eventCoding', note: 'MessageEventCode "case-performed" tells the repository what happened.' },
              { path: 'focus', note: 'Points at the Task carrying the case business status (booked/performed/cancelled).' },
            ],
          },
        },
      ],
    },
  ],
};
